FROM golang:1.17.3-buster

# game server
COPY ./GameServer/ /go/src/

# central game client
COPY ./GameClient/Builds/CentralClient/ /GameClient/
ENV CENTRAL_GAME_CLIENT=1

WORKDIR /go/src/

# for hot reload
RUN go get github.com/githubnemo/CompileDaemon