FROM golang:1.17.3-buster

# copy over server files
COPY ./GameServer/ /go/src/

# copy over unity client files
COPY ./GameClient/Builds/ /GameClient/

# set working directory
WORKDIR /go/src/

# for hot reload
RUN go get github.com/githubnemo/CompileDaemon