version: '3'

services:
  gameserver:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: poc-linux-headless-unity:dev
    container_name: poc-linux-headless-unity
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/go/src
    command: 'CompileDaemon --build="go build -o ./server-build/server"
      --command=./server-build/server'