version: '3'

services:
  gameserver:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: poc-linuc-headless-unity:dev
    container_name: poc-linuc-headless-unity
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/go/src
    command: 'CompileDaemon --build="go build -o ./build/server"
      --command=./build/server'