
public static class Constants
{
    public const string GAME_SERVER_URL = "ws://localhost:5000";
    // message types
    public const string MESSAGE_TYPE_CENTRAL_CLIENT_CONNECT = "MESSAGE_TYPE_CENTRAL_CLIENT_CONNECT";
    public const string MESSAGE_TYPE_PLAYER_CLIENT_CONNECT = "MESSAGE_TYPE_PLAYER_CLIENT_CONNECT";
    public const string MESSAGE_TYPE_PLAYER_INPUT = "MESSAGE_TYPE_PLAYER_INPUT";
    public const string MESSAGE_TYPE_PLAYER_CREATE = "MESSAGE_TYPE_PLAYER_CREATE";
    public const string MESSAGE_TYPE_PLAYER_DESTROY = "MESSAGE_TYPE_PLAYER_DESTROY";
    public const string MESSAGE_TYPE_PLAYER_STATE = "MESSAGE_TYPE_PLAYER_STATE";
    //public const string MESSAGE_TYPE_GAMEBALL_CREATE = "MESSAGE_TYPE_GAMEBALL_CREATE";
    //public const string MESSAGE_TYPE_GAMEBALL_POSITION = "MESSAGE_TYPE_GAMEBALL_POSITION";
}
